# -*- coding: utf-8 -*-
"""CMPE331.02.01.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14iCkZcArRO3YqKo-mSr9reegbnCRkttw

# Worksheet 03C

Stage : Development -01
   @author : Maram Al-MAohgra , 120200123
   @author :  Elif Kırıkkaya ,  119202040
"""

from bs4 import BeautifulSoup #import the BS library

page = 'source.html'
soup = BeautifulSoup(open(page),'lxml')